apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-service-chart.fullname" . }}
  labels:
    {{- include "product-service-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    {{- include "product-service-chart.selectorLabels" . | nindent 4 }}
