name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: product-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: product-service
        run: |
          echo "Running tests..."
          # Add your test commands here (e.g., pytest)

      - name: Build Docker Image
        working-directory: product-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubernetes Config
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Deploy with Helm
        run: |
          helm upgrade --install product-service ./helm-charts/product-service-chart \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/product-service \
            --set image.tag=latest
